name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-22.04
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gerar a Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: Thatielle-Ferreira
          outputs: dist/github-contribution-grid-snake.svg

      # Publicar no branch `output`
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
