name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-22.04 # Define uma versão específica do Ubuntu

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: Thatielle-Ferreira
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the Snake Animation
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
